[package]
name = "lockdown"
description = "Helper library for implementing E2EE Harmony"
version = "0.1.0"
authors = ["Jan Blackquill <uhhadd@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
